### ISSUE TITLE
    NameError: name 'w2i' is not defined

### ISSUE THREAD

**Issue by SidrahJunaid** [meereeum/lda2vec-tf#6]
when trying to run preprocess.py I got this error

**Comment by meereeum** [comment]
`preprocess.py` is a direct fork of cemoody's [original](https://github.com/cemoody/lda2vec/blob/master/lda2vec/preprocess.py) lda2vec. that said, this error is related to doctesting (the examples in the docstring) and should not affect use of the `tokenize` function when imported from `preprocess`
